*&---------------------------------------------------------------------*
*& Report ZAR_COLLECT_OPERATION
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZAR_COLLECT_OPERATION.


TYPES : BEGIN OF TY_COLLECT,
  COMP_NAME TYPE ZAR_EMP_NAME,
  DEPARTMENT TYPE ZAR_DEPARTMENT,
  AMOUNT TYPE ZAR_SALARY,
  END OF TY_COLLECT.

  DATA : LT_COLLECT type of TY_COLLECT,
        LS_COLLECT type TY_COLLECT.
  DATA : LT_COLLECT2 TYPE TABLE OF TY_COLLECT.

  LS_COLLECT-COMP_NAME = 'TCS'.
  LS_COLLECT-DEPARTMENT = 'ABAP'.
  LS_COLLECT-AMOUNT = '20000'.
  APPEND LS_COLLECT to LT_COLLECT.
  CLEAR LS_COLLECT.

  LS_COLLECT-COMP_NAME = 'TCS'.
  LS_COLLECT-DEPARTMENT = 'MM'.
  LS_COLLECT-AMOUNT = '40000'.
  APPEND LS_COLLECT to LT_COLLECT.
  CLEAR LS_COLLECT.

  LS_COLLECT-COMP_NAME = 'TCS'.
  LS_COLLECT-DEPARTMENT = 'ABAP'.
  LS_COLLECT-AMOUNT = '50000'.
  APPEND LS_COLLECT to LT_COLLECT.
  CLEAR LS_COLLECT.

  LS_COLLECT-COMP_NAME = 'TCS'.
  LS_COLLECT-DEPARTMENT = 'BW'.
  LS_COLLECT-AMOUNT = '40000'.
  APPEND LS_COLLECT to LT_COLLECT.
  CLEAR LS_COLLECT.

  LS_COLLECT-COMP_NAME = 'TCS'.
  LS_COLLECT-DEPARTMENT = 'MM'.
  LS_COLLECT-AMOUNT = '30000'.
  APPEND LS_COLLECT to LT_COLLECT.
  CLEAR LS_COLLECT.


  LOOP AT LT_COLLECT into LS_COLLECT.
    COLLECT LS_COLLECT into LT_COLLECT2 .
    CLEAR LS_COLLECT.

  ENDLOOP.
